name: ARM-Mac

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

  repository_dispatch:
    types: [add_ons_push]

  workflow_dispatch:

jobs:
  build_and_test:
    if: contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build plugin for Apple Silicon
    runs-on: macos-latest
    
    steps:
    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout add-ons
      uses: actions/checkout@v2
      with:
        ref: main
        repository: Chowdhury-DSP/BYOD-add-ons
        path: modules/BYOD-add-ons
        token: ${{ secrets.OUR_GITHUB_PAT }}

    - name: Configure
      shell: bash
      run: cmake -Bbuild -GXcode -DBYOD_BUILD_ADD_ON_MODULES=ON -D"CMAKE_OSX_ARCHITECTURES=arm64"

    - name: Build
      shell: bash
      run: cmake --build build --config Debug --parallel | xcpretty
