name: ARM-Mac

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

  workflow_dispatch:

jobs:
  build_and_test:
    if: contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build plugin for Apple Silicon
    runs-on: macos-latest
    
    steps:
    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      shell: bash
      run: cmake -Bbuild -GXcode -D"CMAKE_OSX_ARCHITECTURES=arm64" -DBYOD_BUILD_CLAP=1

    - name: Build
      shell: bash
      run: cmake --build build --config Debug --parallel | xcpretty
