name: CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

  repository_dispatch:
    types: [add_ons_push]

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test plugin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - os: ubuntu-latest
            cmake_args: ""
          - os: windows-2019
            cmake_args: ""
          - os: macos-latest
            cmake_args: "-DCMAKE_BUILD_TYPE=Release"
    
    steps:
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install libasound2-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev libjack-jackd2-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout add-ons
      uses: actions/checkout@v2
      with:
        ref: main
        repository: Chowdhury-DSP/BYOD-add-ons
        path: modules/BYOD-add-ons
        token: ${{ secrets.OUR_GITHUB_PAT }}

    - name: Configure
      shell: bash
      env:
        CMAKE_ARGS: ${{ matrix.cmake_args }}
      run: cmake -Bbuild -DBYOD_BUILD_ADD_ON_MODULES=ON $CMAKE_ARGS

    - name: Build
      shell: bash
      run: cmake --build build --config Release --parallel 4

    - name: Unit Tests
      if: runner.os == 'Linux'
      run: build/BYOD --unit-tests --all

    - name: Validate
      if: runner.os == 'Windows' # || runner.os == 'MacOS'
      run: bash scripts/validate.sh

#    - name: Setup debug session
#      if: always()
#      uses: mxschmitt/action-tmate@v3
